### PR TITLE
Added prometheus exporter README part and added grafana dashboard

### PR DESCRIPTION
**Pull request by lhridder**
- Added grafana dashboard .json
- Added grafana dashboard README.MD
- Added grafana dashboard .png
- Added prometheus exporter part to the main README.md with examples for configuration and metric responses

### CODE REVIEW

**Review by haveachin — APPROVED** [review]
Looks great! We should probably move this into the wiki at a later date to keep the readme clean.

**Comment by lhridder** [comment]
Since it wasn't that much text compared to the rest i thought it would be okay but a wiki page wouldn't hurt indeed

**Comment by haveachin** [comment]
I also want to move the proxy config stuff in the wiki and just link to it from the readme

**Comment by lhridder** [comment]
Maybe keep the docker and add a building from source part in the readme and move all configuration to the wiki

**Pull request merged**
