### PR TITLE
temporary solution to fix #71

### LINKED ISSUE #71: TCPShield Plugin 2.5 not supported
**Describe the bug**
TCPShield Plugin throws an exception when a client joins from a remote network.

**To Reproduce**
Spin up an Infrared proxy with `"realIp": true` and proxy the traffic to a server running TCPShield Plugin 2.5.
In the TCPShield Plugin config set `debug-mode: true` and add `127.0.0.1/32` at the bottom of the `tcpshield-ips.list` file.
Connect through Infrared to the server from a remote network (the client joining the server must have a valid public IP address). This is important due to how the TCPShield Plugin handles local connection.

You should now be able to see this in the server log:
```
[TCPShield] Debug : unknown[unknown/null] was disconnected because no proxy info was received and only-allow-proxy-connections is enabled. Raw payload = "example.com///123.4.567.89:12345///1621048346"
```

**Expected behavior**
Client should be able to connect to the server and his "real" IP should be passed through.

**Additional context** (Optional)
TCPShield Plugin 2.5 code that causes the exception:
https://github.com/TCPShield/RealIP/blob/master/src/main/java/net/tcpshield/tcpshield/TCPShieldPacketHandler.java#L106

### PR DESCRIPTION
**Pull request by gcurtiss**
https://github.com/TCPShield/RealIP/issues/50#issuecomment-846121512

disabling this as detailed here; realIP already handles IP manipulation

### CODE REVIEW

**Comment by haveachin** [comment]
What? What do you think this should fix?

**Comment by gcurtiss** [comment]
Read the issue and comment linked; this should fix incompatiability with TCPShield 2.5

**Comment by haveachin** [comment]
Mhh, I see what you were thinking there and I wish it would be that easy, but I'm sorry to disappoint you - your changes won't fix anything. The problem is not this function. It has something to do this hashing a check value for the RealIP/TCPShield plugin. Removing this function will just break support for any prior version of the plugin.

**Comment by gcurtiss** [comment]
A shame. This would be really nice to see fixed. Whats the alternative for proxying with Infrared and retaining the IP?

**Comment by haveachin** [comment]
You could use proxy protocol.

**Pull request closed without merging**
