### PR TITLE
Update Go version

### PR DESCRIPTION
**Pull request by haveachin**

### CODE REVIEW

**Review by 4kills — COMMENTED** [review]
Nothing wrong with it, but why not upgrade to 1.16 directly?

**Comment by haveachin** [comment]
Good point

**Review by 4kills — DISMISSED** [review]
I have quickly changed that

**Comment by 4kills** [comment]
@haveachin 
It makes no sense upgrading to 1.15 and not 1.16 as docker already builds using 1.16: 
`FROM golang:1.16.0-buster AS builder`
( as can be seen [here](https://github.com/haveachin/infrared/blob/chore/update-go-version/Dockerfile)  )

**Review by 4kills — DISMISSED** [review]
I think this should be fine now. If you don't have any objections, feel free to merge.

**Review by 4kills — APPROVED** [review]

**Pull request merged**
