### PR TITLE
Fix some things

### PR DESCRIPTION
**Pull request by moom0o**
* Replace booleans in docker-compose.yml with integers because it doesn't work with booleans.
* Rename timeout to time in the README because timeout doesn't work.

### CODE REVIEW

**Comment by haveachin** [comment]
Yeah, sorry about the docker compose but INFRARED_DEBUG and INFRARED_COLOR are not supported any more and could be removed all together. The color was buggy in some terminals and debug is now on by default.

**Comment by haveachin** [comment]
The timeout option is working. I don't see a problem with it.

**Comment by moom0o** [comment]
I had to change timeout to time because it kept saying: Invalid proxy config error="time: missing unit in duration \"1000\""
Changing to time fixed it.

**Comment by haveachin** [comment]
Timeout is an integer (time in ms) try removing the quotation marks `"timeout": "1000"` -> `"timeout": 1000`

**Comment by moom0o** [comment]
It didn't have quotes in the first place. Could it be parsing as a string?

**Comment by moom0o** [comment]
I copied and pasted the default config aswell with the same error

**Comment by haveachin** [comment]
Are you sure that you are using the latest version of Infrared?

**Pull request closed without merging**
