### PR TITLE
Add GitHub Actions pipeline for publishing docker images

### PR DESCRIPTION
**Pull request by kstruempf**
Hi :) 
I added a GitHub Actions workflow that builds and publishes a docker image to the GitHub Container Registry and Docker Hub. 
If you are interested I could adapt it so that images will be built and pushed on new releases (git tags) and also push to the already existing repository on Docker Hub.

### CODE REVIEW

**Comment by SirPumpkinHead** [comment]
Just a quick update: I started using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and this [GH Action](https://github.com/mathieudutour/github-tag-action) for automatic generation of releases and changelogs on a personal project. So far it is going well in general, I just ran into a small issue when using PRs. I will keep you posted..

**Comment by haveachin** [comment]
I was also experimenting with this https://github.com/hhn-mc/mailverifier/blob/main/.github/workflows/docker-image.yml and it works great for the Github repository

**Comment by haveachin** [comment]
Hey @SirPumpkinHead, so whats the status on these pipelines? They look pretty promising so far.

**Comment by kstruempf** [comment]
Ok so I spent the afternoon updating the CI pipeline (btw sorry for the many commits, but that was the only way of testing the pipeline - might need to squash the commits). 
The CI pipeline now consists of 3 basic sequential steps (Test, Build, Release).
Test and build run on all PRs into branches `master`, `dev` and `pre-release`.  This basically validates if new changes are buildable.

The release step runs on pushes into `master` and `pre-release`. It creates a changelog and a version number based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and [semantic versioning](https://semver.org/). Docker images are pushed to GHCR and DockerHub. The artifacts produced by goreleaser are uploaded to the github release (this is basically the steps previously configured in [github/workflows/release.yml](https://github.com/haveachin/infrared/blob/master/.github/workflows/release.yml)). 

What you need to configure in the repo are `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` so that images can be pushed to https://hub.docker.com/r/haveachin/infrared. If I have not overlooked anything the pipelines should work :)

**Comment by kstruempf** [comment]
BTW: Docker images are tagged with both the version and the latest tag like so: 
* `haveachin/infrared:latest`
* `haveachin/infrared:0.17.1`
* `ghcr.io/haveachin/infrared:latest`
* `ghcr.io/haveachin/infrared:0.17.1`

**Pull request merged**
